import { readFileSync, statSync } from 'node:fs';
import { runInNewContext } from 'node:vm';

const html = readFileSync('index.html', 'utf8');
const script = readFileSync('script.js', 'utf8');
const translationsSource = script.split('const translations = ')[1]?.split('\n\nconst gallery = ')[0];
if (!translationsSource) throw Error('Translations missing');
const translations = runInNewContext(`(${translationsSource.replace(/;\s*$/, '')})`);
const keys = [...html.matchAll(/data-i18n(?:-aria|-alt)?="([^"]+)"/g)].map(match => match[1]);
for (const lang of ['el','en','de']) for (const key of keys) if (!translations[lang][key]) throw Error(`Missing ${lang} translation: ${key}`);
for (const [, anchor] of html.matchAll(/href="#([^"]+)"/g)) if (!html.includes(`id="${anchor}"`)) throw Error(`Missing anchor: ${anchor}`);
if (!html.includes('Η ΛΙΜΝΗ') || html.includes('noindex')) throw Error('Brand or indexability is incorrect');
if ([...html.matchAll(/data-gallery="(\d+)"/g)].map(match => Number(match[1])).join(',') !== '3,4,5,6,7,0,1,2') throw Error('Expected eight gallery scenes');
const foodStory = html.split('<div class="food-collection food-story page-grid">')[1]?.split('<p class="food-disclosure')[0] || '';
if ([...foodStory.matchAll(/src="assets\/limni\/([^"]+\.webp)"/g)].map(match => match[1]).join(',') !== 'grill-editorial.webp,souvlakia-editorial.webp,panseta-editorial.webp,soutzoukakia-editorial.webp,sheep-cheese-editorial.webp,horiatiki-editorial.webp,bougatsa-editorial.webp') throw Error('Seven food scenes are out of meal order');
if ([...html.matchAll(/data-scene="(day|dusk)"/g)].map(match => match[1]).join(',') !== 'day,dusk' || !script.includes("hero.classList.toggle('is-day'")) throw Error('Hero scene switch missing');
for (const [, image] of html.matchAll(/(?:src|href)="(assets\/limni\/[^\"]+)"/g)) statSync(image);
for (const image of ['hero-dusk-editorial.webp','hero-dusk-editorial-960.webp','weir-editorial.webp','weir-editorial-960.webp','feast-editorial.webp','terrace-editorial.webp','grill-editorial.webp','bougatsa-editorial.webp','souvlakia-editorial.webp','soutzoukakia-editorial.webp','panseta-editorial.webp','sheep-cheese-editorial.webp','horiatiki-editorial.webp','watercolor-cascade.webp','mark.svg','mark-dark.svg']) if (statSync(`assets/limni/${image}`).size < (image.endsWith('.svg') ? 100 : 20_000)) throw Error(`Missing or small image: ${image}`);
if (statSync('assets/texture-grain.svg').size < 100) throw Error('Paper texture missing');
if (html.includes('mark-horizon') || html.includes('keftedakia-two-plates.webp') || !html.includes('foodDisclosure')) throw Error('Old visual direction remains');
if (!html.includes('place-story') || !html.includes('https://tourism.serres.gr/thematikes_empiries/ai-giannis/') || [...html.matchAll(/class="flavour flavour-/g)].length !== 5) throw Error('Place story or five food scenes missing');
if (!html.includes('class="water-chapter media-reveal"') || !html.includes('class="place-story-photo page-grid media-reveal"')) throw Error('Waterfall reveal triggers missing');
const data = JSON.parse(html.match(/<script type="application\/ld\+json">([^<]+)<\/script>/)?.[1] || '{}');
if (data.name !== 'Η ΛΙΜΝΗ' || data['@type'] !== 'Restaurant') throw Error('Restaurant structured data missing');
console.log('Η ΛΙΜΝΗ: assets, gallery, structured data and EL/EN/DE content OK');
